services:
  db:
    # Voi folosi două versiuni diferite pentru baza de date: v1 pentru vulnerable și v2 pentru secure
    image: postgres:latest
    container_name: authx-db-v1
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres  # User-ul default pentru postgres, fără a fi suprascrisă parola
      - POSTGRES_DB=authx_db_v1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_v1:/var/lib/postgresql              # storage-ul bazei de date
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # creearea bazei de date, dacă nu există deja

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-vulnerable
    # Utilizatorul acesta va apărea în terminalul containerului
    user: "razvan-anghel-authx"
    ports:
      - "3000:3000"
    volumes:
      - .:/home/razvan-anghel-authx/app # Folosesc mounting în dev pentru rapiditate
      - /home/razvan-anghel-authx/app/node_modules
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/authx_db_v1
    depends_on:
      - db

volumes:
  postgres_data_v1:
